# Dependencies

In [1]:
import pandas as pd
from glob import glob

pd.options.display.max_columns = 100
pd.options.display.max_colwidth = 200

In [2]:
FOLDER_APPS = '../../icao-reqs-pybossa/pybossa_apps'
FOLDER_CSVS = 'data/recover_taskruns'

OUTPUT_FILE = '../data/pybossa/volunt_and_experts_r1_extra_corr.csv'

# Helper Methods

In [3]:
def load_list_of_csv_as_dataframe(list_csvs):
    df = pd.DataFrame()
    contents = [pd.read_csv(csv_file) for csv_file in list_csvs]
    return df.append(contents)

# Load Data

### icaoreqs_valid_volunt_app

In [4]:
list_csvs = glob(f'{FOLDER_APPS}/icaoreqs_valid_volunt_app/{FOLDER_CSVS}/*.csv')

print(list_csvs)

['../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_volunt_app/data/recover_taskruns\\taskruns_valid_volunt_1.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_volunt_app/data/recover_taskruns\\taskruns_valid_volunt_2.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_volunt_app/data/recover_taskruns\\taskruns_valid_volunt_3.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_volunt_app/data/recover_taskruns\\taskruns_valid_volunt_4.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_volunt_app/data/recover_taskruns\\taskruns_valid_volunt_5.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_volunt_app/data/recover_taskruns\\taskruns_valid_volunt_6.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_volunt_app/data/recover_taskruns\\taskruns_valid_volunt_7.csv']

In [5]:
df_volunteers = load_list_of_csv_as_dataframe(list_csvs)
df_volunteers = df_volunteers[df_volunteers.user_id.isin([3, 5, 6])]

print(df_volunteers.shape)
df_volunteers.head()

(17302, 36)

,img_id,img_origin,img_path,user_id,task_id,created,finish_time,user_ip,link,timeout,project_id,id,answers,blurred,l_away,ink_mark,skin_tone,light,washed_out,pixelation,hair_eyes,eyes_closed,background,rotation,reflection,red_eyes,sh_head,sh_face,dark_glasses,flash_lenses,frames_heavy,frame_eyes,hat,veil,mouth,close
0,0,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-10.png,3,381,2019-09-26T17:15:36.049989,2019-09-26T17:45:12.705487,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/348'/>,NaN,4,348,NaN,1,-1,1,-1,1,1,1,1,-1,1,1,0,-1,1,1,0,0,1,1,1,1,1,1
1,0,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-10.png,6,381,2019-09-30T12:18:22.166826,2019-09-30T12:39:22.014212,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/1595'/>,NaN,4,1595,NaN,1,-1,1,1,1,1,1,1,-1,1,1,0,-1,1,1,0,0,1,-1,1,1,1,1
2,0,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-10.png,5,381,2019-10-02T00:27:36.373347,2019-10-02T00:30:46.428682,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/2457'/>,NaN,4,2457,NaN,1,-1,1,0,0,1,1,-1,-1,1,1,0,-1,1,0,0,0,0,-1,1,1,1,1
4,1,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-13.png,3,382,2019-09-26T17:15:36.369706,2019-09-26T17:54:22.812129,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/349'/>,NaN,4,349,NaN,1,1,1,-1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,-1,1
5,1,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-13.png,6,382,2019-09-30T12:18:22.625423,2019-09-30T12:48:55.596285,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/1596'/>,NaN,4,1596,NaN,1,1,1,-1,1,1,1,1,1,1,-1,0,1,1,1,1,1,1,1,1,0,-1,1

### icaoreqs_valid_expert_app_r1

In [6]:
list_csvs = glob(f'{FOLDER_APPS}/icaoreqs_valid_expert_app_r1/{FOLDER_CSVS}/*.csv')

print(list_csvs)

['../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_1.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_10.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_11.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_12_1.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_12_2.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_2.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_3.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_4.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_5.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_6.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_7.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_8.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1/data/recover_taskruns\\taskruns_valid_expert_r1_9.csv']

In [7]:
df_experts_r1 = load_list_of_csv_as_dataframe(list_csvs)
    
print(df_experts_r1.shape)
df_experts_r1.head()

(11526, 36)

,img_id,img_origin,img_path,user_id,task_id,created,finish_time,user_ip,link,timeout,project_id,id,answers,blurred,l_away,ink_mark,skin_tone,light,washed_out,pixelation,hair_eyes,eyes_closed,background,rotation,reflection,red_eyes,sh_head,sh_face,dark_glasses,flash_lenses,frames_heavy,frame_eyes,hat,veil,mouth,close
0,0,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-10.png,1,6186,2019-11-08T12:18:51.372001,2019-11-08T12:34:13.807661,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/21973'/>,NaN,5,21973,NaN,1,-1,1,0,1,1,1,1,1,1,1,1,-1,1,0,0,0,1,1,1,1,1,-1
1,0,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-10.png,2,6186,2019-11-10T22:02:04.816771,2019-11-10T22:05:42.163341,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/22010'/>,NaN,5,22010,NaN,1,-1,1,0,1,1,1,-1,-1,1,1,0,-1,1,1,0,0,1,-1,1,1,1,1
2,1,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-13.png,1,6187,2019-11-08T12:18:58.602326,2019-11-08T12:37:13.176410,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/21974'/>,NaN,5,21974,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,-1,1
3,1,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-13.png,2,6187,2019-11-10T22:02:04.995246,2019-11-10T22:06:16.909921,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/22011'/>,NaN,5,22011,NaN,1,1,1,-1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,-1,1
4,2,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-15.png,1,6188,2019-11-08T19:08:01.640158,2019-11-08T19:16:11.639618,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/21997'/>,NaN,5,21997,NaN,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1

### icaoreqs_experts_extra_app

In [8]:
list_csvs = glob(f'{FOLDER_APPS}/icaoreqs_experts_extra_app/{FOLDER_CSVS}/*.csv')

print(list_csvs)

['../../icao-reqs-pybossa/pybossa_apps/icaoreqs_experts_extra_app/data/recover_taskruns\\taskruns_experts_extra_1.csv']

In [9]:
df_experts_extra = load_list_of_csv_as_dataframe(list_csvs)

print(df_experts_extra.shape)
df_experts_extra.head()

(19, 36)

,img_id,img_origin,img_path,user_id,task_id,created,finish_time,user_ip,link,timeout,project_id,id,answers,blurred,l_away,ink_mark,skin_tone,light,washed_out,pixelation,hair_eyes,eyes_closed,background,rotation,reflection,red_eyes,sh_head,sh_face,dark_glasses,flash_lenses,frames_heavy,frame_eyes,hat,veil,mouth,close
0,0,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-001-4.png,1,13724,2019-11-21T19:12:10.900409,2019-11-21T19:14:17.218869,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23853'/>,NaN,7,23853,NaN,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1
1,1,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-001-8.png,1,13725,2019-11-21T19:12:11.135600,2019-11-21T19:14:47.504754,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23855'/>,NaN,7,23855,NaN,1,-1,1,1,1,1,1,1,-1,1,1,1,-1,1,1,0,1,1,-1,1,1,1,1
2,2,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-005-20.png,1,13726,2019-11-21T19:14:17.491761,2019-11-21T19:15:03.323248,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23857'/>,NaN,7,23857,NaN,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1
3,3,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-009-8.png,1,13727,2019-11-21T19:14:47.761447,2019-11-21T19:15:27.886739,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23859'/>,NaN,7,23859,NaN,1,-1,1,1,0,1,1,1,-1,0,1,1,-1,1,1,0,1,1,-1,1,1,1,1
4,4,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-018-1_PX6.png,1,13728,2019-11-21T19:15:03.545055,2019-11-21T19:15:44.031239,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23860'/>,NaN,7,23860,NaN,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

### icaoreqs_valid_expert_app_r1_corr

In [10]:
list_csvs = glob(f'{FOLDER_APPS}/icaoreqs_valid_expert_app_r1_corr/{FOLDER_CSVS}/*.csv')

print(list_csvs)

['../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1_corr/data/recover_taskruns\\taskruns_valid_expert_r1_1.csv', '../../icao-reqs-pybossa/pybossa_apps/icaoreqs_valid_expert_app_r1_corr/data/recover_taskruns\\taskruns_valid_expert_r1_2.csv']

In [11]:
df_experts_corr = load_list_of_csv_as_dataframe(list_csvs)

print(df_experts_corr.shape)
df_experts_corr.head()

(25, 36)

,img_id,img_origin,img_path,user_id,task_id,created,finish_time,user_ip,link,timeout,project_id,id,answers,blurred,l_away,ink_mark,skin_tone,light,washed_out,pixelation,hair_eyes,eyes_closed,background,rotation,reflection,red_eyes,sh_head,sh_face,dark_glasses,flash_lenses,frames_heavy,frame_eyes,hat,veil,mouth,close
0,503,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-046-19.png,1,13884,2020-02-06T18:33:10.395604,2020-02-06T18:34:19.729600,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/33668'/>,NaN,10,33668,NaN,1,1,1,0,1,1,1,1,1,0,1,0,1,1,0,1,0,1,1,1,1,1,1
1,505,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-046-22.png,1,13885,2020-02-06T18:33:10.749026,2020-02-06T18:34:44.066613,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/33669'/>,NaN,10,33669,NaN,1,-1,1,1,1,1,1,-1,-1,0,1,1,-1,1,1,0,0,1,-1,1,1,1,1
0,1345,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/FRGC_04256d137_px_4.png,2,13886,2020-02-07T12:18:36.508920,2020-02-07T12:19:26.596182,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/33670'/>,NaN,10,33670,NaN,1,1,1,1,0,1,0,1,1,0,1,1,1,-1,0,1,1,1,1,1,1,1,1
1,1349,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/FRGC_04256d168.jpg,2,13887,2020-02-07T12:18:36.664328,2020-02-07T12:19:59.419757,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/33671'/>,NaN,10,33671,NaN,1,1,1,0,1,1,1,1,1,0,1,0,1,-1,0,1,1,1,1,1,1,1,1
2,1358,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/FRGC_04261d276_px_8.png,2,13888,2020-02-07T12:19:26.776466,2020-02-07T12:20:25.574078,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/33672'/>,NaN,10,33672,NaN,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1

# Append All

In [12]:
df = pd.concat([df_volunteers, df_experts_r1, df_experts_extra, df_experts_corr])
df.finish_time = pd.to_datetime(df.finish_time)

print(df.shape)
df.head()

(28872, 36)

,img_id,img_origin,img_path,user_id,task_id,created,finish_time,user_ip,link,timeout,project_id,id,answers,blurred,l_away,ink_mark,skin_tone,light,washed_out,pixelation,hair_eyes,eyes_closed,background,rotation,reflection,red_eyes,sh_head,sh_face,dark_glasses,flash_lenses,frames_heavy,frame_eyes,hat,veil,mouth,close
0,0,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-10.png,3,381,2019-09-26T17:15:36.049989,2019-09-26 17:45:12.705487,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/348'/>,NaN,4,348,NaN,1,-1,1,-1,1,1,1,1,-1,1,1,0,-1,1,1,0,0,1,1,1,1,1,1
1,0,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-10.png,6,381,2019-09-30T12:18:22.166826,2019-09-30 12:39:22.014212,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/1595'/>,NaN,4,1595,NaN,1,-1,1,1,1,1,1,1,-1,1,1,0,-1,1,1,0,0,1,-1,1,1,1,1
2,0,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-10.png,5,381,2019-10-02T00:27:36.373347,2019-10-02 00:30:46.428682,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/2457'/>,NaN,4,2457,NaN,1,-1,1,0,0,1,1,-1,-1,1,1,0,-1,1,0,0,0,0,-1,1,1,1,1
4,1,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-13.png,3,382,2019-09-26T17:15:36.369706,2019-09-26 17:54:22.812129,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/349'/>,NaN,4,349,NaN,1,1,1,-1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,-1,1
5,1,train,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/train/AR_FDB_m-001-13.png,6,382,2019-09-30T12:18:22.625423,2019-09-30 12:48:55.596285,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/1596'/>,NaN,4,1596,NaN,1,1,1,-1,1,1,1,1,1,1,-1,0,1,1,1,1,1,1,1,1,0,-1,1

# Sanity Checks

In [13]:
df_votes = df.sort_values(by=['img_path', 'user_id', 'project_id', 'finish_time'])
df_votes.drop_duplicates(subset=['img_path', 'user_id'], keep='last', inplace=True)

df_votes['votes'] = df_votes.groupby('img_path')['user_id'].transform('count')

In [14]:
df_errors = df_votes[df_votes.votes != 5]

print(df_errors.shape)
df_errors

(19, 37)

,img_id,img_origin,img_path,user_id,task_id,created,finish_time,user_ip,link,timeout,project_id,id,answers,blurred,l_away,ink_mark,skin_tone,light,washed_out,pixelation,hair_eyes,eyes_closed,background,rotation,reflection,red_eyes,sh_head,sh_face,dark_glasses,flash_lenses,frames_heavy,frame_eyes,hat,veil,mouth,close,votes
0,0,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-001-4.png,1,13724,2019-11-21T19:12:10.900409,2019-11-21 19:14:17.218869,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23853'/>,NaN,7,23853,NaN,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1
1,1,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-001-8.png,1,13725,2019-11-21T19:12:11.135600,2019-11-21 19:14:47.504754,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23855'/>,NaN,7,23855,NaN,1,-1,1,1,1,1,1,1,-1,1,1,1,-1,1,1,0,1,1,-1,1,1,1,1,1
2,2,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-005-20.png,1,13726,2019-11-21T19:14:17.491761,2019-11-21 19:15:03.323248,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23857'/>,NaN,7,23857,NaN,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,3,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-009-8.png,1,13727,2019-11-21T19:14:47.761447,2019-11-21 19:15:27.886739,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23859'/>,NaN,7,23859,NaN,1,-1,1,1,0,1,1,1,-1,0,1,1,-1,1,1,0,1,1,-1,1,1,1,1,1
4,4,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-018-1_PX6.png,1,13728,2019-11-21T19:15:03.545055,2019-11-21 19:15:44.031239,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23860'/>,NaN,7,23860,NaN,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
5,5,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-027-13.png,1,13729,2019-11-21T19:15:28.125744,2019-11-21 19:16:35.332378,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23862'/>,NaN,7,23862,NaN,1,1,1,-1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,-1,1,1
6,6,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-040-16.png,1,13730,2019-11-21T19:15:44.255152,2019-11-21 19:23:33.001272,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23880'/>,NaN,7,23880,NaN,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1
7,7,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-048-17.png,1,13731,2019-11-21T19:16:35.580650,2019-11-21 19:25:23.499376,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23885'/>,NaN,7,23885,NaN,1,-1,1,1,1,1,1,1,0,0,1,1,-1,1,1,1,1,1,1,1,1,0,1,1
8,8,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_m-069-14_C40.png,1,13732,2019-11-21T19:30:38.092920,2019-11-21 19:31:22.801657,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23893'/>,NaN,7,23893,NaN,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
9,9,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_w-004-3.png,1,13733,2019-11-21T19:30:39.345995,2019-11-21 19:31:36.741095,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23895'/>,NaN,7,23895,NaN,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,0,1,1,1,1,1,1,1
10,10,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_w-013-4.png,1,13734,2019-11-21T19:31:23.034028,2019-11-21 19:33:40.616161,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23901'/>,NaN,7,23901,NaN,1,-1,1,1,1,1,1,-1,0,1,1,1,-1,1,1,1,1,1,-1,1,1,0,1,1
11,11,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_w-028-2.png,1,13735,2019-11-21T19:31:37.007883,2019-11-21 19:34:03.583408,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23903'/>,NaN,7,23903,NaN,1,1,1,1,0,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1
12,12,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/AR_w-059-12.png,1,13736,2019-11-21T19:33:40.840255,2019-11-21 19:34:29.814664,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23905'/>,NaN,7,23905,NaN,1,1,1,-1,1,1,1,0,1,0,1,1,1,1,-1,1,1,1,1,1,0,-1,1,1
13,13,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/Fall2002_04207d110.JPG,1,13737,2019-11-21T19:34:03.832272,2019-11-21 19:35:01.803424,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23907'/>,NaN,7,23907,NaN,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1
14,14,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/Fall2002_04221d128.JPG,1,13738,2019-11-21T19:34:30.109580,2019-11-21 19:35:32.556326,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23908'/>,NaN,7,23908,NaN,1,1,1,1,0,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1
15,15,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/Fall2002_04243d108.JPG,1,13739,2019-11-21T19:35:02.075186,2019-11-21 19:36:15.411333,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23911'/>,NaN,7,23911,NaN,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,0,1,1,1,1
16,16,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/Fall2002_04386d35.JPG,1,13740,2019-11-21T19:35:32.792879,2019-11-21 19:36:51.852668,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23912'/>,NaN,7,23912,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,0,1,1
17,17,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/Fall2003_04237d106.jpg,1,13741,2019-11-21T19:36:15.693508,2019-11-21 19:37:13.155028,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23913'/>,NaN,7,23913,NaN,1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1
18,18,validation,http://pesquisa.eastus.cloudapp.azure.com:8081/icao_dataset/validation/PUT_00201020.JPG,1,13742,2019-11-21T19:36:52.078284,2019-11-21 19:37:38.557125,NaN,<link rel='self' title='taskrun' href='http://pesquisa2.eastus.cloudapp.azure.com/api/taskrun/23914'/>,NaN,7,23914,NaN,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1

In [15]:
df_final = df_votes[df_votes.votes == 5]

assert(df_final.user_id.nunique() == 5)
assert(df_final.img_path.nunique() == 5763)
assert(df_final.groupby('img_path')['user_id'].count().max() == 5)
assert(df_final.groupby('img_path')['user_id'].count().min() == 5)

# Save

In [16]:
df_final.to_csv(OUTPUT_FILE, index=False)